services:
  myproxy:
    build: 
      context: .
      dockerfile: Dockerfile
      tags:
        - localhost:32000/joplin-proxy:1.2.2
        - localhost:32000/joplin-proxy:latest
    image: localhost:32000/joplin-proxy:1.2.2
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"

